rmr/apps/books/urls.py
# -*- coding: utf-8 -*-
"""
    apps.books.urls
    ~~~~~~~~~~~~~~

    desciption
    
    :copyright: (c) 2012 by arruda.
"""

from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('books.views', 
 
   url(r'^$', 'mybooks', name='my_books'),     
   url(r'^search/$', 'filter', name='filter_books'),     
   url(r'^new/$', 'new', name='new_book'),       
##   url(r'^edit/(?P<id_book>\d+)/$', 'edit', name='edit_book'),       
   url(r'^mark_bought/(?P<id_book>\d+)/$', 'mark_as_bought', name='mark_as_bought'),  
   url(r'^must_read/(?P<id_book>\d+)/$', 'mark_as_must_read', name='mark_as_must_read'),       
   url(r'^new_genre_ajax/$', 'new_genre_ajax', name='ajax_new_genre'),        
)

rmr/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.views.generic.simple import direct_to_template

from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       
     url(r'^', include('accounts.urls')),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^books/', include('books.urls')),
     url(r'^authors/', include('authors.urls')),
     url(r'^publishers/', include('publishers.urls')),
     url(r'^stores/', include('stores.urls')),
     url(r'^reports/', include('reports.urls')),
     url(r'^faqs/$', direct_to_template, {'template': 'faqs.html'}, name='faqs'),
     url(r'^test/$', direct_to_template, {'template': 'test.html'}, name='test'),
)


urlpatterns += patterns('django.contrib.auth.views',               

    url(r'^login/$', 'login', {'template_name': 'users/login.html',}, name='login'),  
    url(r'^logout/$', 'logout', {'template_name': 'users/login.html'},name='logout'),
        

)

if settings.SERVE_MEDIA:
    
    urlpatterns += staticfiles_urlpatterns()

rmr/apps/books/models.py
# -*- coding: utf-8 -*-
"""
    apps.books.models
    ~~~~~~~~~~~~~~

    books models
    
    :copyright: (c) 2012 by arruda.
"""
from decimal import  Decimal
import datetime

from django.db import models

from django.utils.translation import ugettext_lazy as _

from model_utils import Choices

from utils.abs_models import Abs_Named_Model, Abs_UniqueNamed_Model


class Genre(Abs_UniqueNamed_Model):
    "define a genre, like: action, romance, etc.."
    
    class Meta:
        app_label = 'books'
        ordering = ['name',]
        
        
class Book(Abs_Named_Model):
    "a book. simple as that"
    
    
    author = models.ForeignKey('authors.Author',related_name='books')
    publisher = models.ForeignKey('publishers.Publisher',related_name='books')
    
    synopsis = models.TextField(_('Synopsis'), null=True,blank=True)
    genres = models.ManyToManyField(Genre)
    
    release_date =  models.DateField(_("Release Date"), default=datetime.date.today, null=True, blank=True)
    
    
    def just_released(self):
        "returns True if the release_date - this date is less then one year"
        release_time=datetime.timedelta(days=365)
        return datetime.date.today() - self.release_date < release_time
    
    just_released.short_description = 'Just Released?'
    
    class Meta:
        app_label = 'books'
        ordering = ['name',]
        unique_together = (('name','author' ),)
    
        
class UserBook(models.Model):
    "Relation between user and book"
    
    DESIRE_CHOICES = Choices(
                             (1,'curious',_("1 - Curious About")),
                             (2,'collection',_("2 - Complete Collection")),
                             (3,'survive',_("3 - Can Survive Without It")),
                             (4,'wait',_("4 - Can Wait a Little Longer")),
                             (5,'now',_("5 - I NEED THIS... NOW!!!")),
                     )
    
    user = models.ForeignKey('auth.User',related_name='books')
    book = models.ForeignKey(Book,related_name='users')
    
    desired = models.PositiveSmallIntegerField(_("Desired"), choices=DESIRE_CHOICES, default=DESIRE_CHOICES.curious)
    
    #purchase data
    purchase_store = models.ForeignKey('stores.Store',related_name='books',null=True,blank=True)
    purchased       = models.BooleanField(_("Purchased?"),default=False)
    purchase_value = models.DecimalField(_("Purchase Value"),max_digits=10, decimal_places=2, null=True, blank=True)
    purchase_date =  models.DateField(_("Purchase Date"),  null=True, blank=True)#, default=datetime.date.today,)
    
    class Meta:
        app_label = 'books'
        
    @property
    def desired_text(self):
        "return the correct self.desired text"
        return self.DESIRE_CHOICES[self.desired-1][1].__unicode__()
        
    def save(self, *args, **kwargs):
        """
        if has any purchased information, then mark as purchased
        """
        #if has a purchase value or date then mark as purchased
        if self.purchase_value or self.purchase_date or self.purchase_store:
            self.purchased = True
        
        super(UserBook, self).save(*args, **kwargs)
        
        

rmr/apps/books/views.py
# -*- coding: utf-8 -*-
"""
    apps.books.views
    ~~~~~~~~~~~~~~

    views for books
    
    :copyright: (c) 2012 by arruda.
"""

import datetime

from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from annoying.decorators import render_to


from utils.decorators import ajax_login_required, JsonResponse

from books.forms import NewBookForm, NewGenreForm, BookFilterForm, UserBookFilterForm, MarkAsBoughtBookForm, MarkAsMustReadForm

from books.models import Book, UserBook

@login_required
@render_to("books/list.html")
def filter(request):
    "list the books of the system"
    
    
    filter_params = {}
    
    filter_form = BookFilterForm(request.user,request.GET)
        
    user_books = request.user.books.all()
    
    if filter_form.is_valid():        
        books = filter_form.get_books()
        
    return locals()

    
@login_required
@render_to("books/my_books.html")
def mybooks(request):
    "list the books of the logged user"
    
    
    filter_params = {}
    
    filter_form = UserBookFilterForm(request.user,request.GET)
    
    if filter_form.is_valid():        
        books = filter_form.get_books()
        
    return locals()

@login_required
@render_to("books/new.html")
def new(request):
    "create a new book for the system"
    
    if request.method == 'POST':
        form = NewBookForm(request.POST)
        if form.is_valid():             
            book = form.save()
            return redirect('filter_books')
    else:
        form = NewBookForm()
    
    return locals()

#
#@login_required
#@render_to("books/edit.html")
#def edit(request,id_book):
#    "edit a given book for the logged user"
#    
#    book = get_object_or_404(Book,pk=id_book)
#    if request.method == 'POST':
#        form = NewBookForm(request.user,request.POST,instance=book)
#        if form.is_valid():             
#            book = form.save(commit=False)
#            book.user = request.user
#            book.save()
#            form.save_m2m()
#            return redirect('filter_books')
#    else:
#        form = NewBookForm(request.user,instance=book)
#    
#    return locals()

#


@login_required
@render_to("books/mark_bought.html")
def mark_as_bought(request,id_book):
    "mark a given userbook as bought"
    book = get_object_or_404(UserBook,pk=id_book)
    
    if request.user != book.user:
        return redirect('filter_books')
    if request.method == 'POST':
        form = MarkAsBoughtBookForm(request.POST,instance=book)
        if form.is_valid():             
            book = form.save(commit=False)
            book.purchased = True
            book.save()            
            form.save_m2m()
            return redirect('filter_books')
    else:
        if not book.purchase_date:
            book.purchase_date = datetime.date.today()
        form = MarkAsBoughtBookForm(instance=book)
    
    return locals()
    
    
@ajax_login_required
def mark_as_must_read(request,id_book):
    "mark a given book as must read"
    book = get_object_or_404(Book,pk=id_book)
    
    if request.method == 'POST':
        form = MarkAsMustReadForm(request.POST)
        if form.is_valid():             
            userBook = form.save(commit=False)
            userBook.user = request.user
            userBook.book = book
            
            userBook.save()            
            form.save_m2m()
            return JsonResponse({'ok':True})
        else:
            return JsonResponse({'errors': form.errors})
            
    
    return JsonResponse({})

@login_required
@render_to("books/new_genre.html")
def new_genre(request):
    "create a new genre for the system"
    
    if request.method == 'POST':
        form = NewGenreForm(request.POST)
        if form.is_valid():             
            genre = form.save()
            return redirect('filter_books')
    else:
        form = NewGenreForm()
    
    return locals()

    
@ajax_login_required
def new_genre_ajax(request):
    "create a new genre for the system, using ajax"
    
    if request.method == 'POST':
        form = NewGenreForm(request.POST)
        if form.is_valid():             
            object = form.save()
            return JsonResponse({'model':"genre",'id':object.id, 'name':object.name})
        else:
            return JsonResponse({'errors': form.errors})
    
    return JsonResponse({})

rmr/templates/books/edit.html
{% extends "util/base.html"%}

{% block 'body-content' %}
	<h1>Editing: {{book.name}}</h1>
	

	<div>
		<form action="{% url edit_book book.id %}" method="post" id="edit-bk-form">
			{% csrf_token %}
			<li>
				{{ form.name.errors }}
				{{ form.name.label_tag }} {{ form.name }} 				
			</li>
			<li>
				{{ form.desired.errors }}
				{{ form.desired.label_tag }} {{ form.desired }} 		
			</li>	
			<li>
				{{ form.author.errors }}
				{{ form.author.label_tag }} {{ form.author }} <a href="#"  class="add-another" id="new_author">+</a>				
			</li>
			<li>
				{{ form.publisher.errors }}
				{{ form.publisher.label_tag }} {{ form.publisher }} <a href="#"  class="add-another" id="new_publisher">+</a>		
			</li>			
			<li>
				{{ form.synopsis.errors }}
				{{ form.synopsis.label_tag }} {{ form.synopsis }}
			</li>
			
			<li>
				{{ form.genres.errors }}
				{{ form.genres.label_tag }} {{ form.genres }} <a href="#"  class="add-another" id="new_genre">+</a>		
			</li>	
			
			<li>
				{{ form.release_date.errors }}
				{{ form.release_date.label_tag }} {{ form.release_date }} 		
			</li>	
			
			<li>
				{{ form.purchase_store.errors }}
				{{ form.purchase_store.label_tag }} {{ form.purchase_store }} <a href="#"  class="add-another" id="new_purchase_store">+</a>
			</li>	
			
			<li>
				{{ form.purchased.errors }}
				{{ form.purchased.label_tag }} {{ form.purchased }}
			</li>	
			
			<li>
				{{ form.purchase_value.errors }}
				{{ form.purchase_value.label_tag }} {{ form.purchase_value }}
			</li>	
			
			<li>
				{{ form.purchase_date.errors }}
				{{ form.purchase_date.label_tag }} {{ form.purchase_date }}
			</li>	
			
			
			<input type="submit" value="Save" />
		</form>
	</div>
	
    <div id="model-dialog-modal" title="New Model">
        <form id="model-dl-form">
            <ul style="list-style:none;">
                <li>
                    <label for="name">Name</label>
                    <input id="id_name" type="text" name="name" maxlength="250" />
                </li>
            </ul>
        </form>
    </div>
{% endblock %}

{% block 'jquery-docready' %}
{{ block.super }}

            $( "#model-dialog-modal" ).dialog({
                autoOpen: false,
                modal: true,
                buttons: {
                    Ok: function() {   
                    	var selected_model = $( this ).data("selected_model");                     
                        var new_form = $("#model-dl-form");
						var url_author = '{% url ajax_new_author %}';
						var url_publisher = '{% url ajax_new_publisher %}';
						var url_genre = '{% url ajax_new_genre %}';
						var url_store = '{% url ajax_new_store %}';
						
						var post_url;
						if(selected_model == "author"){
							post_url = url_author;
						}
						else if(selected_model == "publisher"){
							post_url = url_publisher;
						}
						else if(selected_model == "genre"){
							post_url = url_genre;
						}
						else if(selected_model == "store"){
							post_url = url_store;
						}

                        $.post(post_url,
                            new_form.serialize(),
                            function(data) {
                            	if(data.errors !== undefined){
					                //for each field in the errrors
				                    $.each(data.errors, function(key, value) { 
				                       	var field = new_form;
			
				                       	//if it's not a general error, than add it to the expecific field
				                       	//else just add it to the form
				                    	if(key != "__all__"){
				                       		var field = new_form.find("[name='" + key + "']").parent();
				                    	}
			
				                        //add each error to the given field
				                        $.each(value, function(index, val){
				                           field.prepend("<span class='error'>"+val+"</span>");
			
				                        });
				                    });
			                    }
                            	else{
	                                console.log(data);
	
	
	 								var model_list;
	 								
	                                //add the new model to it's correct list
	                                if(selected_model == "author"){
	 									model_list = $("#edit-bk-form #id_author");
	                                
	                                }else if(selected_model == "publisher"){
	 									model_list = $("#edit-bk-form #id_publisher");
	                                
	                                }else if(selected_model == "genre"){
	 									model_list = $("#edit-bk-form #id_genres");
	                                
	                                }else if(selected_model == "store"){
	 									model_list = $("#edit-bk-form #id_purchase_store");
	                                
	                                }
	                               
	                                
	                                model_list.append("<option value='"+ data.id +"' selected>"+ data.name +"</option>");
	
	                                $( "#model-dialog-modal" ).dialog( "close" );
	                                
                            	}

                            },"json");
                

                    },
                    Cancel: function() {
                        $( this ).dialog( "close" );
                    }
                },
                close: function() {                   
                    $( this ).dialog( "close" );
                    var new_form = $( this ).find("#model-dl-form");

                    new_form.find("input").val("");
                    new_form.find(".error").remove();   
                    console.log("close");
                }
            });
	
		
                
            //change the add buttons to add new contents
            $('#new_author').click(function(evt){
                evt.preventDefault();
                
                var dialog = $( "#model-dialog-modal" );
                console.log("new_author");          
                      
                $('.ui-dialog-title').html("New Author");  
                dialog.data("selected_model","author");
                dialog.dialog( "open" );    
            });
                
            //change the add buttons to add new contents
            $('#new_publisher').click(function(evt){
                evt.preventDefault();
                
                var dialog = $( "#model-dialog-modal" );
                console.log("new_publisher");          
                      
                $('.ui-dialog-title').html("New Publisher");  
                dialog.data("selected_model","publisher");
                dialog.dialog( "open" );    
            });
            
            //change the add buttons to add new contents
            $('#new_genre').click(function(evt){
                evt.preventDefault();
                
                var dialog = $( "#model-dialog-modal" );
                console.log("new_genre");          
                      
                $('.ui-dialog-title').html("New Genre");  
                dialog.data("selected_model","genre");
                dialog.dialog( "open" );    
            });
            
            //change the add buttons to add new contents
            $('#new_purchase_store').click(function(evt){
                evt.preventDefault();
                
                var dialog = $( "#model-dialog-modal" );
                console.log("new_purchase_store");          
                      
                $('.ui-dialog-title').html("New Store");  
                dialog.data("selected_model","store");
                dialog.dialog( "open" );    
            });
            
		    $("#model-dl-form").live("click", function(evt){
		        evt.preventDefault();
		    });
		    
			//datepicker			
	        $( "#id_purchase_date" ).datepicker({
	            showOn: "button",
	            buttonImage: "{{ STATIC_URL}}images/calendar.png",
	            buttonImageOnly: true,
	            dateFormat: "dd/mm/yy"
	        });	
	        $( "#id_release_date" ).datepicker({
	            showOn: "button",
	            buttonImage: "{{ STATIC_URL}}images/calendar.png",
	            buttonImageOnly: true,
	            dateFormat: "dd/mm/yy"
	        });
	        

{% endblock %}

rmr/templates/books/mark_bought.html
{% extends "util/base.html"%}

{% block 'body-content' %}
	<h1>Purchased: {{book.book.name}} - {{book.book.author}}</h1>
	

	<div>
		<form action="{% url mark_as_bought book.id %}" method="post" id="purchase-bk-form">
			{% csrf_token %}
			<li>
				{{ form.purchase_store.errors }}
				{{ form.purchase_store.label_tag }} {{ form.purchase_store }} <a href="#"  class="add-another" id="new_purchase_store">+</a>		
			</li>
			<li>
				{{ form.purchase_value.errors }}
				{{ form.purchase_value.label_tag }} {{ form.purchase_value }} 		
			</li>	
			<li>
				{{ form.purchase_date.errors }}
				{{ form.purchase_date.label_tag }} {{ form.purchase_date }}				
			</li>
			<input type="submit" value="Save" />
		</form>
	</div>
    <div id="model-dialog-modal" title="New Model">
        <form id="model-dl-form">
            <ul style="list-style:none;">
                <li>
                    <label for="name">Name</label>
                    <input id="id_name" type="text" name="name" maxlength="250" />
                </li>
            </ul>
        </form>
    </div>
	
{% endblock %}

{% block 'jquery-docready' %}
{{ block.super }}

			//new model dialog
            $( "#model-dialog-modal" ).dialog({
                autoOpen: false,
                modal: true,
                buttons: {
                    Ok: function() {   
                    	var selected_model = $( this ).data("selected_model");                     
                        var new_form = $("#model-dl-form");
						var url_author = '{% url ajax_new_author %}';
						var url_publisher = '{% url ajax_new_publisher %}';
						var url_genre = '{% url ajax_new_genre %}';
						var url_store = '{% url ajax_new_store %}';
						
						var post_url;
						if(selected_model == "author"){
							post_url = url_author;
						}
						else if(selected_model == "publisher"){
							post_url = url_publisher;
						}
						else if(selected_model == "genre"){
							post_url = url_genre;
						}
						else if(selected_model == "store"){
							post_url = url_store;
						}

                        $.post(post_url,
                            new_form.serialize(),
                            function(data) {
                            	if(data.errors !== undefined){
					                //for each field in the errrors
				                    $.each(data.errors, function(key, value) { 
				                       	var field = new_form;
			
				                       	//if it's not a general error, than add it to the expecific field
				                       	//else just add it to the form
				                    	if(key != "__all__"){
				                       		var field = new_form.find("[name='" + key + "']").parent();
				                    	}
			
				                        //add each error to the given field
				                        $.each(value, function(index, val){
				                           field.prepend("<span class='error'>"+val+"</span>");
			
				                        });
				                    });
			                    }
                            	else{
	                                console.log(data);
	
	
	 								var model_list;
	 								
	                                //add the new model to it's correct list
	                                if(selected_model == "store"){
	 									model_list = $("#purchase-bk-form #id_purchase_store");
	                                
	                                }
	                               
	                                
	                                model_list.append("<option value='"+ data.id +"' selected>"+ data.name +"</option>");
	
	                                $( "#model-dialog-modal" ).dialog( "close" );
	                                
                            	}

                            },"json");
                

                    },
                    Cancel: function() {
                        $( this ).dialog( "close" );
                    }
                },
                close: function() {                   
                    $( this ).dialog( "close" );
                    var new_form = $( this ).find("#model-dl-form");

                    new_form.find("input").val("");
                    new_form.find(".error").remove();   
                    console.log("close");
                }
            });
	
		
            
            //change the add buttons to add new contents
            $('#new_purchase_store').click(function(evt){
                evt.preventDefault();
                
                var dialog = $( "#model-dialog-modal" );
                console.log("new_purchase_store");          
                      
                $('.ui-dialog-title').html("New Store");  
                dialog.data("selected_model","store");
                dialog.dialog( "open" );    
            });
            
		    $("#model-dl-form").live("click", function(evt){
		        evt.preventDefault();
		    });


			//datepicker			
	        $( "#id_purchase_date" ).datepicker({
	            showOn: "button",
	            buttonImage: "{{ STATIC_URL}}images/calendar.png",
	            buttonImageOnly: true,
	            dateFormat: "dd/mm/yy"
	        });

{% endblock %}

rmr/templates/books/new.html
{% extends "util/base.html"%}

{% block 'body-content' %}
	<h1>New Book</h1>
	

	<div>
		<form action="{% url new_book %}" method="post" id="newbk-form">
			{% csrf_token %}
			<li>
				{{ form.name.errors }}
				{{ form.name.label_tag }} {{ form.name }} 				
			</li>
			<li>
				{{ form.author.errors }}
				{{ form.author.label_tag }} {{ form.author }} <a href="#"  class="add-another" id="new_author">+</a>				
			</li>
			<li>
				{{ form.publisher.errors }}
				{{ form.publisher.label_tag }} {{ form.publisher }} <a href="#"  class="add-another" id="new_publisher">+</a>		
			</li>			
			<li>
				{{ form.synopsis.errors }}
				{{ form.synopsis.label_tag }} {{ form.synopsis }}
			</li>
			
			<li>
				{{ form.genres.errors }}
				{{ form.genres.label_tag }} {{ form.genres }} <a href="#"  class="add-another" id="new_genre">+</a>		
			</li>	
			
			<li>
				{{ form.release_date.errors }}
				{{ form.release_date.label_tag }} {{ form.release_date }} 		
			</li>	
			
			<input type="submit" value="Create" />
		</form>
	</div>
	
    <div id="model-dialog-modal" title="New Model">
        <form id="model-dl-form">
            <ul style="list-style:none;">
                <li>
                    <label for="name">Name</label>
                    <input id="id_name" type="text" name="name" maxlength="250" />
                </li>
            </ul>
        </form>
    </div>
{% endblock %}

{% block 'jquery-docready' %}
{{ block.super }}

            $( "#model-dialog-modal" ).dialog({
                autoOpen: false,
                modal: true,
                buttons: {
                    Ok: function() {   
                    	var selected_model = $( this ).data("selected_model");                     
                        var new_form = $("#model-dl-form");
						var url_author = '{% url ajax_new_author %}';
						var url_publisher = '{% url ajax_new_publisher %}';
						var url_genre = '{% url ajax_new_genre %}';
						var url_store = '{% url ajax_new_store %}';
						
						var post_url;
						if(selected_model == "author"){
							post_url = url_author;
						}
						else if(selected_model == "publisher"){
							post_url = url_publisher;
						}
						else if(selected_model == "genre"){
							post_url = url_genre;
						}

                        $.post(post_url,
                            new_form.serialize(),
                            function(data) {
                            	if(data.errors !== undefined){
					                //for each field in the errrors
				                    $.each(data.errors, function(key, value) { 
				                       	var field = new_form;
			
				                       	//if it's not a general error, than add it to the expecific field
				                       	//else just add it to the form
				                    	if(key != "__all__"){
				                       		var field = new_form.find("[name='" + key + "']").parent();
				                    	}
			
				                        //add each error to the given field
				                        $.each(value, function(index, val){
				                           field.prepend("<span class='error'>"+val+"</span>");
			
				                        });
				                    });
			                    }
                            	else{
	                                console.log(data);
	
	
	 								var model_list;
	 								
	                                //add the new model to it's correct list
	                                if(selected_model == "author"){
	 									model_list = $("#newbk-form #id_author");
	                                
	                                }else if(selected_model == "publisher"){
	 									model_list = $("#newbk-form #id_publisher");
	                                
	                                }else if(selected_model == "genre"){
	 									model_list = $("#newbk-form #id_genres");
	                                
	                                }else if(selected_model == "store"){
	 									model_list = $("#newbk-form #id_purchase_store");
	                                
	                                }
	                               
	                                
	                                model_list.append("<option value='"+ data.id +"' selected>"+ data.name +"</option>");
	
	                                $( "#model-dialog-modal" ).dialog( "close" );
	                                
                            	}

                            },"json");
                

                    },
                    Cancel: function() {
                        $( this ).dialog( "close" );
                    }
                },
                close: function() {                   
                    $( this ).dialog( "close" );
                    var new_form = $( this ).find("#model-dl-form");

                    new_form.find("input").val("");
                    new_form.find(".error").remove();   
                    console.log("close");
                }
            });
	
		
                
            //change the add buttons to add new contents
            $('#new_author').click(function(evt){
                evt.preventDefault();
                
                var dialog = $( "#model-dialog-modal" );
                console.log("new_author");          
                      
                $('.ui-dialog-title').html("New Author");  
                dialog.data("selected_model","author");
                dialog.dialog( "open" );    
            });
                
            //change the add buttons to add new contents
            $('#new_publisher').click(function(evt){
                evt.preventDefault();
                
                var dialog = $( "#model-dialog-modal" );
                console.log("new_publisher");          
                      
                $('.ui-dialog-title').html("New Publisher");  
                dialog.data("selected_model","publisher");
                dialog.dialog( "open" );    
            });
            
            //change the add buttons to add new contents
            $('#new_genre').click(function(evt){
                evt.preventDefault();
                
                var dialog = $( "#model-dialog-modal" );
                console.log("new_genre");          
                      
                $('.ui-dialog-title').html("New Genre");  
                dialog.data("selected_model","genre");
                dialog.dialog( "open" );    
            });
            
            
		    $("#model-dl-form").live("click", function(evt){
		        evt.preventDefault();
		    });

			//datepicker			
	        $( "#id_release_date" ).datepicker({
	            showOn: "button",
	            buttonImage: "{{ STATIC_URL}}images/calendar.png",
	            buttonImageOnly: true,
	            dateFormat: "dd/mm/yy"
	        });
{% endblock %}

rmr/templates/books/new_genre.html
{% extends "util/base.html"%}

{% block 'body-content' %}
	<h1>New Genre</h1>
	

	<div>
		<form action="{% url new_genre %}" method="post" id="newgenre-form">
			{% csrf_token %}
			{{ form.as_ul }}
			<input type="submit" value="Create" />
		</form>
	</div>
{% endblock %}